import { useColorScheme } from "react-native";

// ─────────────────────────────────────────────
// THEME COLORS
// ─────────────────────────────────────────────

export const DARK_COLORS = {
  primary: "#F5C518",
  dark: "#1A1A1A",
  darkCard: "#242424",
  surface: "#2E2E2E",
  border: "#3A3A3A",
  textPrimary: "#FFFFFF",
  textSecondary: "#AAAAAA",
  success: "#4CAF50",
  error: "#FF5252",
  accent: "#00B0FF",
  headerBg: "#111111",
  screenBg: "#1A1A1A",
  inputBg: "#2E2E2E",
  inputBorder: "#3A3A3A",
  inputText: "#FFFFFF",
  contractBg: "#1A1A1A",
  contractHeaderBg: "#242424",
  contractBtnRowBg: "#242424",
  contractBodyText: "#BBBBBB",
  contractTitleText: "#FFFFFF",
  contractBorderBottom: "#3A3A3A",
  checkboxBorder: "#666",
  checkLabel: "#CCCCCC",
  qualIntro: "#AAAAAA",
  qualFieldLabel: "#AAAAAA",
  uploadFieldBg: "#2E2E2E",
  uploadFieldBorder: "#444",
  uploadFieldText: "#FFFFFF",
  notPossessText: "#AAAAAA",
  notesInputBg: "#2E2E2E",
  notesInputBorder: "#444",
  notesInputText: "#FFFFFF",
  uniformNotice: "#AAAAAA",
  uniformGridName: "#5B8EFF",
  uniformGridPrice: "#FFFFFF",
  searchBarBg: "#2E2E2E",
  searchBarBorder: "#444",
  searchInputText: "#FFFFFF",
  timerBarBg: "#1e2a4a",
  timerText: "#5B8EFF",
  qLabel: "#5B8EFF",
  qText: "#FFFFFF",
  assessOptionBg: "#2E2E2E",
  assessOptionBorder: "#555",
  assessOptionText: "#FFFFFF",
  assessOptionSelectedBg: "#2E2E2E",
  assessOptionSelectedBorder: "#5B8EFF",
  assessOptionSelectedText: "#5B8EFF",
  resultSubText: "#CCCCCC",
  pendingBadgeBg: "#F7D02A",
  pendingBadgeText: "#000",
  contractNameInputBg: "#2E2E2E",
  contractNameInputBorder: "#555",
  contractNameInputText: "#FFF",
};

export const LIGHT_COLORS = {
  primary: "#F5C518",
  dark: "#F9F9F9",
  darkCard: "#1F222A",
  surface: "#EAEAEA",
  border: "#D3D3D3",
  textPrimary: "#1A1A1A",
  textSecondary: "#666666",
  success: "#4CAF50",
  error: "#FF5252",
  accent: "#00B0FF",
  headerBg: "#FFFFFF",
  screenBg: "#F5F5F5",
  inputBg: "#F6F6F7",
  inputBorder: "#D3D3D3",
  inputText: "#111111",
  contractBg: "#FFFFFF",
  contractHeaderBg: "#FFFFFF",
  contractBtnRowBg: "#FFFFFF",
  contractBodyText: "#444444",
  contractTitleText: "#111111",
  contractBorderBottom: "#DDDDDD",
  checkboxBorder: "#CCCCCC",
  checkLabel: "#444444",
  qualIntro: "#444444",
  qualFieldLabel: "#797A88",
  uploadFieldBg: "#F6F6F7",
  uploadFieldBorder: "#DDDDDD",
  uploadFieldText: "#111111",
  notPossessText: "#797A88",
  notesInputBg: "#F7F7F7",
  notesInputBorder: "#DDDDDD",
  notesInputText: "#111111",
  uniformNotice: "#676774",
  uniformGridName: "#2563EB",
  uniformGridPrice: "#111111",
  searchBarBg: "#F7F7F7",
  searchBarBorder: "#DDDDDD",
  searchInputText: "#111111",
  timerBarBg: "#EEF2FF",
  timerText: "#2563EB",
  qLabel: "#2563EB",
  qText: "#111111",
  assessOptionBg: "#FAFAFA",
  assessOptionBorder: "#9E9FAA",
  assessOptionText: "#000000",
  assessOptionSelectedBg: "#FAFAFA",
  assessOptionSelectedBorder: "#2563EB",
  assessOptionSelectedText: "#2563EB",
  resultSubText: "#212121",
  pendingBadgeBg: "#F7D02A",
  pendingBadgeText: "#000",
  contractNameInputBg: "#FFF",
  contractNameInputBorder: "#CCC",
  contractNameInputText: "#111",
};

// ─────────────────────────────────────────────
// HOOK
// ─────────────────────────────────────────────

export const useThemeColors = () => {
  const scheme = useColorScheme();
  return scheme === "light" ? LIGHT_COLORS : DARK_COLORS;
};
